spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login
#person:
#  name: gjw${random.uuid}
#  age: ${random.int}
#  happy: false
#  birth: 2021/07/04
#  hello: 123
#  maps: {k1: v1,k2: v2}
#  list:
#    - code
#    - music
#    - girl
#  dog:
#    name: ${person.hello:hel}
#    age: 3
#server:
#  port: 8080
#spring:
#  profiles:
#    active: test
#---
#server:
#  port: 8081
#spring:
#  config:
#    activate:
#      on-profile: dev
#---
#server:
#  port: 8082
#spring:
#  config:
#    activate:
server:
  port: 8081
#      on-profile: test